import Head from "next/head";
import GlobalStyle from "../globalStyles";
import StyledWrapper from "./../pageStyles/projectStyles";
import { projectList } from "./../data/projectList";
import { DESCRIPTION } from "../data/descriptions";
import ProjectCard from "../components/ProjectCard";

const Projects = () => {
  return (
    <>
      <Head>
        <title>Projects - Shashank Kashyap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={DESCRIPTION.PROJECTS} />
        <meta property="og:description" content={DESCRIPTION.PROJECTS} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="www.shashankkashyap.com/projects" />
      </Head>

      <GlobalStyle />

      <StyledWrapper className="container">
        <div className="projects-page container-main">
          <h1>My Projects</h1>
          <div className="content-list">
            {projectList.map(({ id, title, dateTime, description, link }) => {
              return (
                <ProjectCard
                  key={id}
                  title={title}
                  dateTime={dateTime}
                  description={description}
                  link={link}
                />
              );
            })}
          </div>
        </div>
      </StyledWrapper>
    </>
  );
};

export default Projects;
